### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by mamaretti** [Spiker985/x-terminal-reloaded#101]
hi
can you help me please?

I'm not able to install

im on 1.114.0
macOS 12.7.

`> node-pty-prebuilt-multiarch@0.10.0 install /private/var/folders/y4/njxk1z9d1vlflm6jv8gzm89h0000gr/T/apm-install-dir-2024123-12647-wzuuvb.lic5h/node_modules/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

undefined

prebuild-install WARN install No prebuilt binaries found (target=12.2.3 runtime=electron arch=x64 libc= platform=darwin)
gyp ERR! build error 
gyp ERR! stack Error: spawn Unknown system error -86
gyp ERR! stack at ChildProcess.spawn (node:internal/child_process:415:11)
gyp ERR! stack at Object.spawn (node:child_process:609:9)
gyp ERR! stack at Gyp.spawn (/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:175:27)
gyp ERR! stack at doBuild (/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/lib/build.js:202:22)
gyp ERR! stack at async doWhich (/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/lib/build.js:115:5)
gyp ERR! stack at async loadConfigGypi (/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/lib/build.js:78:7)
gyp ERR! stack at async build (/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/lib/build.js:36:3)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/Applications/Pulsar.app/Contents/Resources/app/ppm/bin/node" "/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/y4/njxk1z9d1vlflm6jv8gzm89h0000gr/T/apm-install-dir-2024123-12647-wzuuvb.lic5h/node_modules/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v16.0.0
gyp ERR! node-gyp -v v9.4.0
gyp ERR! not ok 
npm WARN notsup Unsupported engine for which@3.0.1: wanted: {"node":"^14.17.0 || ^16.13.0 || >=18.0.0"} (current: {"node":"16.0.0","npm":"6.14.19-pulsar1-1"})
npm WARN notsup Not compatible with your version of node/npm: which@3.0.1
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/y4/njxk1z9d1vlflm6jv8gzm89h0000gr/T/apm-install-dir-2024123-12647-wzuuvb.lic5h/package.json'
npm WARN apm-install-dir-2024123-12647-wzuuvb.lic5h No description
npm WARN apm-install-dir-2024123-12647-wzuuvb.lic5h No repository field.
npm WARN apm-install-dir-2024123-12647-wzuuvb.lic5h No README data
npm WARN apm-install-dir-2024123-12647-wzuuvb.lic5h No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.10.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.10.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

thx

**Comment by btypoon** [comment]
I have similar issue. I cannot install this package onto my pulsar-edit.

> npm WARN deprecated xterm-addon-fit@0.7.0: This package is now deprecated. Move to @xterm/addon-fit instead.
> npm WARN deprecated xterm-addon-ligatures@0.6.0: This package is now deprecated. Move to @xterm/addon-ligatures instead.
> npm WARN deprecated xterm@5.2.1: This package is now deprecated. Move to @xterm/xterm instead.
> npm WARN deprecated xterm-addon-web-links@0.8.0: This package is now deprecated. Move to @xterm/addon-web-links instead.
> npm WARN deprecated xterm-addon-webgl@0.15.0: This package is now deprecated. Move to @xterm/addon-webgl instead.
> npm WARN deprecated npmlog@4.1.2: This package is no longer supported.
> npm WARN deprecated gauge@2.7.4: This package is no longer supported.
> npm WARN deprecated are-we-there-yet@1.1.7: This package is no longer supported.
> npm WARN notsup Unsupported engine for which@3.0.1: wanted: {"node":"^14.17.0 || ^16.13.0 || >=18.0.0"} (current: {"node":"16.0.0","npm":"6.14.19-pulsar1-1"})
> npm WARN notsup Not compatible with your version of node/npm: which@3.0.1
> npm WARN enoent ENOENT: no such file or directory, open 'D:\Temp\apm-install-dir-202516-21508-13wmyu1.kfwq\package.json'
> npm WARN apm-install-dir-202516-21508-13wmyu1.kfwq No description
> npm WARN apm-install-dir-202516-21508-13wmyu1.kfwq No repository field.
> npm WARN apm-install-dir-202516-21508-13wmyu1.kfwq No README data
> npm WARN apm-install-dir-202516-21508-13wmyu1.kfwq No license field.
> 
> npm ERR! code EBUSY
> npm ERR! syscall rename
> npm ERR! path D:\Temp\apm-install-dir-202516-21508-13wmyu1.kfwq\node_modules\.x-terminal-reloaded.DELETE\node_modules\isexe
> npm ERR! dest D:\Temp\apm-install-dir-202516-21508-13wmyu1.kfwq\node_modules\x-terminal-reloaded\node_modules\isexe
> npm ERR! errno -4082
> npm ERR! EBUSY: resource busy or locked, rename 'D:\Temp\apm-install-dir-202516-21508-13wmyu1.kfwq\node_modules\.x-terminal-reloaded.DELETE\node_modules\isexe' -> 'D:\Temp\apm-install-dir-202516-21508-13wmyu1.kfwq\node_modules\x-terminal-reloaded\node_modules\isexe'

I am using windows 11, pulsar 1.125.0, python 3.13 and installed visual studio 2022.

**Comment by TheJasonPlayz** [comment]
Same issue here

**Comment by aknight2015** [comment]
Debian 12
Same issue.

[2025-05-25T04_51_27_569Z-debug.log](https://github.com/user-attachments/files/20429407/2025-05-25T04_51_27_569Z-debug.log)
