### ISSUE TITLE
[BR] Installation Failed

### ISSUE THREAD

**Issue by zhaolinlau** [Spiker985/x-terminal-reloaded#12]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
- [x] I have tried uninstalling/reinstalling the terminal.
- [ ] I have not tried uninstalling/reinstalling the terminal.
### Steps to reproduce

1. type apm install x-terminal
2. press enter

**Expected behavior:**
Installing minimap to C:\Users\Win10\.pulsar\packages done

**Actual behavior:**
Installing x-terminal to C:\Users\Win10\.pulsar\packages failed

```
> node-pty-prebuilt-multiarch@0.10.0 install C:\Users\Win10\AppData\Local\Temp\apm-install-dir-20221127-11076-18kod9.ens8a\node_modules\x-terminal\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


C:\Users\Win10\AppData\Local\Temp\apm-install-dir-20221127-11076-18kod9.ens8a\node_modules\x-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

prebuild-install WARN install No prebuilt binaries found (target=12.2.3 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:5)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
gyp ERR! System Windows_NT 10.0.22621
gyp ERR! command "C:\\Users\\Win10\\AppData\\Local\\Programs\\pulsar\\resources\\app\\ppm\\bin\\node.exe" "C:\\Users\\Win10\\AppData\\Local\\Programs\\pulsar\\resources\\app\\ppm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Win10\AppData\Local\Temp\apm-install-dir-20221127-11076-18kod9.ens8a\node_modules\x-terminal\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v16.0.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Win10\AppData\Local\Temp\apm-install-dir-20221127-11076-18kod9.ens8a\package.json'
npm WARN apm-install-dir-20221127-11076-18kod9.ens8a No description
npm WARN apm-install-dir-20221127-11076-18kod9.ens8a No repository field.
npm WARN apm-install-dir-20221127-11076-18kod9.ens8a No README data
npm WARN apm-install-dir-20221127-11076-18kod9.ens8a No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.10.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.10.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Win10\.pulsar\.apm\_logs\2022-12-27T03_32_23_890Z-debug.log
```

**Reproduces how often:**
100%

### Versions

```
PS C:\Users\Win10> pulsar --version
PS C:\Users\Win10>
Pulsar  : 1.100.0-beta
Electron: 12.2.3
Chrome  : 89.0.4389.128
Node    : 14.16.0

```

```
PS C:\Users\Win10> apm --version
apm  2.7.0
npm  6.14.9
node 16.0.0 x64
atom 1.100.0-beta
python 3.10.9
git 2.38.1.windows.1
visual studio

```
OS name and version: Windows 11 22H2
Terminal version: PowerShell 7.3.1

### Additional context
![image](https://user-images.githubusercontent.com/68846168/209607478-f69ba105-05b7-47a0-a9b1-9b012b5041a6.png)

**Comment by Spiker985** [comment]
@zhaolinlau So, in my testing, I had to downgrade to Visual Studio 2019 for the time being. The reason is that ppm bundled with Pulsar is utilizing an older version of npm, and it only detects up to 2019.

Once we get ppm updated, we'll be able to use 2022 as well. I'm sorry for the inconvenience.

**Comment by zhaolinlau** [comment]
> @zhaolinlau So, in my testing, I had to downgrade to Visual Studio 2019 for the time being. The reason is that ppm bundled with Pulsar is utilizing an older version of npm, and it only detects up to 2019.
> 
> Once we get ppm updated, we'll be able to use 2022 as well. I'm sorry for the inconvenience.

But on Atom 1.60, why it doesn't even need to pre-install visual studio to install terminal package?

**Comment by Spiker985** [comment]
@zhaolinlau Alright, so I figured out the `why` behind why Atom 1.60 didn't need to use the C++ build chain. And that is because previously, version 0.10.0 of `node-pty-prebuilt-multiarch` contained the headers required for the version of Electron that Atom was on.

When we forked Pulsar, we were able to update the underlying node and electron versions - up to electron 12.2.3/node 14.16/Chrome 89.0.4389.128. Version `0.10.1-pre.5` contains the new headers, the original `0.10.0` did not

I'm in the process of working to bump this

**Comment by zhaolinlau** [comment]
When will this issue being fixed?

**Comment by asiloisad** [comment]
Is there any progress with this bug? I cannot install the package too

**Comment by cristobalstrange** [comment]
> Is there any progress with this bug? I cannot install the package too

Installing node.js and npm fixed this for me

**Comment by confused-Techie** [comment]
As this hasn't been mentioned here yet.

The error above is exactly about the Visual Studio version.

The newest version of Pulsar (1.110.0) upgrades PPM's copy of `node-gyp` meaning we can now use Visual Studio 2022.

@Spiker985 I think we are good to call this one resolved now

**Comment by Spiker985** [comment]
Closing due to our above upgrades within 1.110.0, if the problem appears to reoccur please don't hesitate to ping me
