### ISSUE TITLE
ValueError: invalid mode: 'rU' while trying to load binding.gyp

### ISSUE THREAD

**Issue by utkarsh-singh07** [Spiker985/x-terminal-reloaded#47]
Error popped out after tried to installing x-terminal-reloaded,

```bash
> node-pty-prebuilt-multiarch@0.9.0 install /tmp/apm-install-dir-202345-183836-dbispu.krhy9/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


prebuild-install WARN install No prebuilt binaries found (target=12.2.3 runtime=electron arch=x64 libc= platform=linux)
(node:183995) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
Traceback (most recent call last):
  File "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 6.2.12-200.fc37.x86_64
gyp ERR! command "/opt/Pulsar/resources/app/ppm/bin/node" "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-202345-183836-dbispu.krhy9/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v16.0.0
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-202345-183836-dbispu.krhy9/package.json'
npm WARN apm-install-dir-202345-183836-dbispu.krhy9 No description
npm WARN apm-install-dir-202345-183836-dbispu.krhy9 No repository field.
npm WARN apm-install-dir-202345-183836-dbispu.krhy9 No README data
npm WARN apm-install-dir-202345-183836-dbispu.krhy9 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/utkarsh/.pulsar/.apm/_logs/2023-05-05T03_47_44_704Z-debug.log
```

**Comment by timefreer** [comment]
Having same issue in Ubuntu 23.04. I tried globally installing node-gyp, node-pty, and node-pty-prebuilt-multiarch with no change in error. Next guess is that it wants electron to already be installed, but haven't tried that.

**Comment by Spiker985** [comment]
Something that is extremely confusing is the inclusion of `platformio-ide-terminal` inside the provided error message

Our two packages are separate, and ppm shouldn't be attempting to use any modules from platformio-ide-terminal

**Comment by jigyasu-singh** [comment]
@Spiker985 , i have tried to install `plateform-io-ide` terminal before i tried to install `x-terminal-reloaded` in fedora 37.

**Comment by nreef12** [comment]
I'm having the same issue and I'm on macOS 13.2.1...

<details>
<summary>output</summary>
```
> node-pty-prebuilt-multiarch@0.10.0 install /private/var/folders/_7/qfyb532d0r748fr_5phbnyx80000gn/T/apm-install-dir-2023516-5826-1nfrsd6.awvv/node_modules/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


prebuild-install WARN install No prebuilt binaries found (target=12.2.3 runtime=electron arch=x64 libc= platform=darwin)
(node:5850) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
Traceback (most recent call last):
  File "/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 22.3.0
gyp ERR! command "/Applications/Pulsar.app/Contents/Resources/app/ppm/bin/node" "/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/_7/qfyb532d0r748fr_5phbnyx80000gn/T/apm-install-dir-2023516-5826-1nfrsd6.awvv/node_modules/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v16.0.0
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/_7/qfyb532d0r748fr_5phbnyx80000gn/T/apm-install-dir-2023516-5826-1nfrsd6.awvv/package.json'
npm WARN apm-install-dir-2023516-5826-1nfrsd6.awvv No description
npm WARN apm-install-dir-2023516-5826-1nfrsd6.awvv No repository field.
npm WARN apm-install-dir-2023516-5826-1nfrsd6.awvv No README data
npm WARN apm-install-dir-2023516-5826-1nfrsd6.awvv No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.10.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.10.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nreef/.pulsar/.apm/_logs/2023-06-16T22_09_51_940Z-debug.log
``` 
</details>

**Comment by PythonAtSea** [comment]
I'm having the same issue on Ubuntu 23.04

**Comment by Digitalone1** [comment]
Me too in v1.106.0 on Arch Linux.

**Comment by magowiz** [comment]
Searching for `ValueError: invalid mode: 'rU' while trying to load binding.gyp` error I was able to find a solution here: https://stackoverflow.com/questions/74715990/node-gyp-err-invalid-mode-ru-while-trying-to-load-binding-gyp

It comes out that pulsar uses a node-gyp that uses a deprecate mode (since python3.3) that was removed completely in python3.11, recent ubuntu ships 3.11 as default python version and I suppose also other people facing this issue are using python3.11.
In the link I shared with you there are some ways to workaround this. Since for another project I needed python3.10, I choose the method to set the `NODE_GYP_FORCE_PYTHON` to my python3.10 executable, then I was able to install x-terminal-reloaded without issues. I hope you will be able to workaround as well, until a fix is found.

**Comment by confused-Techie** [comment]
@magowiz Is correct here.

Over on Pulsar we have had to stay at Python 3.10, since Python 3.11 introduces breaking changes to `node-gyp`. But since `ppm` doesn't bundle a Python version, that means users need to make sure Python 3.10 is available to build native modules in Pulsar.

**Comment by Spiker985** [comment]
Additionally you can also set the python environment `PYTHON=$(which python3.10)` if using arch linux with it installed, before launching pulsar (or ppm), and it will accomplish the same.

Upstream issue with Pulsar, just happens to affect this package - will close as resolved due to the workaround
