### ISSUE TITLE
Won't install on Debian Sid

### ISSUE THREAD

**Issue by tripplehelix** [Spiker985/x-terminal-reloaded#79]
I'm running Debian GNU/Linux trixie/sid x86_64
```
node --version
v20.7.0

npm version
{
  'x-terminal-reloaded': '14.2.6',
  npm: '10.1.0',
  node: '20.7.0',
  acorn: '8.10.0',
  ada: '2.6.0',
  ares: '1.19.1',
  base64: '0.5.0',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '8.1.1',
  modules: '115',
  napi: '9',
  nghttp2: '1.55.1',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.10+quic',
  simdutf: '3.2.17',
  tz: '2023c',
  undici: '5.23.0',
  unicode: '15.0',
  uv: '1.46.0',
  uvwasi: '0.0.18',
  v8: '11.3.244.8-node.15',
  zlib: '1.2.13.1-motley'
}
```

```
21:36:48:~/.pulsar/packages/x-terminal-reloaded ʎ npm list
x-terminal-reloaded@14.2.6 /home/tom/.pulsar/packages/x-terminal-reloaded
├── @semantic-release/apm-config@9.0.1
├── atom-jasmine3-test-runner@5.2.13
├── deep-object-diff@1.1.9
├── eslint-config-standard@17.1.0
├── eslint-plugin-import@2.28.1
├── eslint-plugin-json@3.1.0
├── eslint-plugin-n@16.0.2
├── eslint-plugin-promise@6.1.1
├── eslint@8.48.0
├── fs-extra@11.1.1
├── marked@4.3.0
├── node-pty-prebuilt-multiarch@0.10.0
├── postcss-less@6.0.0
├── semantic-release@21.1.1
├── stylelint-config-standard@34.0.0
├── stylelint-stylistic@0.4.3
├── stylelint@15.10.3
├── temp@0.9.4
├── uuid@9.0.0
├── whatwg-url@12.0.1
├── which@3.0.1
├── xterm-addon-fit@0.7.0
├── xterm-addon-ligatures@0.6.0
├── xterm-addon-web-links@0.8.0
├── xterm-addon-webgl@0.15.0
└── xterm@5.2.1
```

The error when I try to install:

```
21:31:55:~/.pulsar/packages/x-terminal-reloaded ʎ pulsar --package rebuild
Rebuilding modules ✗
prebuild-install WARN install No prebuilt binaries found (target=12.2.3 runtime=electron arch=x64 libc= platform=linux)
(node:21845) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
Traceback (most recent call last):
  File "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 6.5.0-1-amd64
gyp ERR! command "/opt/Pulsar/resources/app/ppm/bin/node" "/opt/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tom/.pulsar/packages/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v16.0.0
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.10.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.10.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tom/.pulsar/.apm/_logs/2023-09-24T20_32_08_891Z-debug.log
```

**Comment by confused-Techie** [comment]
I'd first make sure you have exactly Python 3.10 installed.

3.11 despite it's semver broke `node-gyp` which is used to build native modules within NodeJS packages, like this one.

**Comment by tripplehelix** [comment]
> I'd first make sure you have exactly Python 3.10 installed.
> 
> 3.11 despite it's semver broke `node-gyp` which is used to build native modules within NodeJS packages, like this one.

I've compiled the python 3.10 binary, how do I use it to install this? I need python3.11 as most of my system requires it. Is there an option to tell it which python binary to use?

**Comment by tripplehelix** [comment]
Great! That fixed it. Is this issue going to be resolved or is it a problem on python's end?

For future reference: https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux

**Comment by confused-Techie** [comment]
@tripplehelix While I'm not the most versed in this issue, from my understanding this stems from incompatibility between `node-gyp` and Python 3.11

So ideally the fix could come from either end, although I don't know the exact specifics of it. So keeping an eye on either end can hopefully provide some clarity. Sorry I'm not more familiar with the exact nature of the issue, and more just know the solution and it's side effects.

If you are on the Pulsar Discord, asking in the PPM channel may provide others more familiar with the issue to help shed some light on this.
