### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by liquidmetalrob** [Spiker985/x-terminal-reloaded#96]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Pulsar package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Pulsar**: 1.111.0 x64
**Electron**: 12.2.3
**OS**: Microsoft Windows 10 Home
**Thrown From**: [x-terminal-reloaded](https://github.com/Spiker985/x-terminal-reloaded) package 14.3.0

### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:292

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:456:14)
    at WindowsTerminal._doWrite (/packages/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch/lib/windowsTerminal.js:115:30)
    at WindowsTerminal._defer (/packages/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch/lib/windowsTerminal.js:157:24)
    at WindowsTerminal._write (/packages/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch/lib/windowsTerminal.js:112:14)
    at WindowsTerminal.Terminal.write (/packages/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch/lib/terminal.js:82:14)
    at element.js:493:21
    at t.EventEmitter.fire (/packages/x-terminal-reloaded/node_modules/xterm/lib/xterm.js:1:138854)
    at /packages/x-terminal-reloaded/node_modules/xterm/lib/xterm.js:1:138989
    at t.EventEmitter.fire (/packages/x-terminal-reloaded/node_modules/xterm/lib/xterm.js:1:138854)
    at d.triggerDataEvent (/packages/x-terminal-reloaded/node_modules/xterm/lib/xterm.js:1:259224)
    at I._keyDown (/packages/x-terminal-reloaded/node_modules/xterm/lib/xterm.js:1:41940)
    at /packages/x-terminal-reloaded/node_modules/xterm/lib/xterm.js:1:28401)
```

### Commands

```
     -6:05.0 x-terminal-reloaded:open (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-hot-package-loader 0.5.1 
atom-minify 0.8.0 
atom-overtype-mode 0.4.0 
grammar-token-limit 0.1.1 
language-babel 2.85.0 
multi-cursor 3.0.0 
persistent-undo 1.5.0 
print 2.0.0 
rainbow-tabs-evolved 2.7.19 
remember-folds 0.3.0 
script 13.3.7 
swap-selection 0.4.0 
x-terminal-reloaded 14.3.0 
```

**Comment by DeeDeeG** [comment]
This seems to be a network error? (Given the "socket" bit, and the stack trace pointing into `net.js`.)

Are you able to try on another machine, and/or on another network?
